# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oRNHbHUpuO2qDw_EtBoysrSgV4t8BgZE
"""

# Bin python code 
def nextfit(weight, c):
	res = 0
	rem = c
	for _ in range(len(weight)):
		if rem >= weight[_]:
			rem = rem - weight[_]
		else:
			res += 1
			rem = c - weight[_]
	return res

# Input
weight = [3, 4, 5, 8, 2, 1, 3]
c = 10

print("No. of bins required in Next best Fit :",
						nextfit(weight, c))